name: Validate

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  yaml:
    name: YAML
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: Validate YAML
        run: yamllint themes .github/workflows

  hacs:
    name: HACS
    runs-on: ubuntu-latest

    steps:
      - name: Validate HACS repository
        uses: hacs/action@main
        with:
          category: theme
